spin_manifest_version = 2

[application]
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""
name = "spin-kv-counter-py"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-kv-counter-py"

[component.spin-kv-counter-py]
source = "app.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.spin-kv-counter-py.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
watch = ["*.py", "requirements.txt"]
